services:
  - type: web
    name: MonitorIED_bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: 7275139009:AAFw4U4n2zMhdzN1uTdNXySkwVKx5fMwMpk
      - key: ADMIN_IDS
        value: 522223534,342445163
